name: Build and Release .NET Framework 4.7.1

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: windows-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild dotnet-4.7.1.sln /p:Configuration=Release

    - name: Run Console app (smoke)
      run: .\ConsoleApp\bin\Release\ConsoleApp.exe

    - name: Run WPF app (smoke)
      run: .\WpfApp\bin\Release\WpfApp.exe || true

    - name: Determine next version tag
      id: version
      shell: bash
      run: |
        set -euo pipefail
        # try to get latest tag starting with v
        latest=$(git describe --tags --match "v[0-9]*" --abbrev=0 2>/dev/null || true)
        echo "latest tag: $latest"
        if [ -z "$latest" ]; then
          next="v0.1.0"
        else
          ver=${latest#v}
          IFS='.' read -r major minor patch <<< "$ver"
          patch=$((patch+1))
          next="v${major}.${minor}.${patch}"
        fi
        echo "new_tag=$next" >> $GITHUB_OUTPUT
        echo "new_tag=$next"

    - name: Create and push tag
      if: always()
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        tag=${{ steps.version.outputs.new_tag }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # if tag already exists on remote, skip creating/pushing
        if git ls-remote --tags origin | grep -q "refs/tags/$tag$"; then
          echo "Tag $tag already exists on remote; skipping tag creation."
        else
          git tag -a "$tag" -m "Release $tag"
          # push tag using token
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$tag"
        fi

    - name: Ensure release exists
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        tag=${{ steps.version.outputs.new_tag }}
        if gh release view "$tag" >/dev/null 2>&1; then
          echo "Release $tag already exists"
        else
          gh release create "$tag" --title "$tag" --notes "Automated release from GitHub Actions"
        fi

    - name: Upload release assets with gh
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        tag=${{ steps.version.outputs.new_tag }}
        gh release upload "$tag" ConsoleApp/bin/Release/ConsoleApp.exe WpfApp/bin/Release/WpfApp.exe --clobber
