name: WPF headless check

on:
  push:
  pull_request:

jobs:
  wpf-check:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore dotnet-4.7.1.sln

    - name: Build solution
      run: msbuild dotnet-4.7.1.sln /p:Configuration=Release

    - name: Run headless WPF check
      run: |
        echo Running WpfApp.exe --ci
        .\WpfApp\bin\Release\WpfApp.exe --ci
      shell: cmd
